export TUDataset

"""
    TUDataset

A variety of graph kernel benchmark datasets, *.e.g.* "IMDB-BINARY",
"REDDIT-BINARY" or "PROTEINS", collected from the [TU Dortmund University](https://chrsmrrs.github.io/datasets).
"""
module TUDataset

using DataDeps
using ..MLDatasets: datafile, datadir
using DelimitedFiles: readdlm

using PyCall

const DEPNAME = "TUDataset"
# LINK = "https://github.com/shchur/gnn-benchmark/raw/master/data/npz"
# LINK = "https://github.com/abojchevski/graph2gauss/raw/master/data/"
const LINK = "https://www.chrsmrrs.com/graphkerneldatasets"
const DOCS = "https://chrsmrrs.github.io/datasets"
const DATA = "PROTEINS.zip"

function __init__()
    register(DataDep(
        DEPNAME,
        """
        Dataset: The $DEPNAME dataset.
        Website: $DOCS
        """,
        "$LINK/$DATA",
        # "81de017067dc045ebdb8ffd5c0e69a209973ffdb1fe2d5b434e94d3614f3f5c7",  # if checksum omitted, will be generated by DataDeps
        post_fetch_method = unpack
    ))
end

struct TUData
    source::Vector{Int}
    target::Vector{Int}
    graph_indicator::Vector{Int}
    node_labels::Vector{Int}
    edge_labels::Union{Nothing, Vector{Int}}
    graph_labels::Vector{Int}
    node_attributes
    edge_attributes
    graph_attributes
end

"""
    dataset(name; dir=nothing)

Retrieve the TUDataset dataset. The output is a named tuple with fields

See [this link](https://chrsmrrs.github.io/datasets/docs/datasets/)
for a list of the available datasets.
"""
function dataset(name; dir=nothing) 
    d = datadir(DEPNAME, dir)
    # See here for the file format https://chrsmrrs.github.io/datasets/docs/format/
    st = readdlm(joinpath(d, name, "$(name)_A.txt"), ',', Int)

    # LOAD OPTIONAL FILES IF EXIST
    
    if isfile(joinpath(d, name, "$(name)_edge_labels.txt"))
        edge_labels = readdlm(joinpath(d, name, "$(name)_edge_labels.txt")) |> vec
    else
        edge_labels = nothing
    end
    if isfile(joinpath(d, name, "$(name)_node_attributes.txt"))
        node_attributes = readdlm(joinpath(d, name, "$(name)_node_attributes.txt"), Float32)' |> collect
    else
        node_attributes = nothing
    end
    if isfile(joinpath(d, name, "$(name)_edge_attributes.txt"))
        edge_attributes = readdlm(joinpath(d, name, "$(name)_edge_attributes.txt"), Float32)' |> collect
    else
        edge_attributes = nothing
    end
    if isfile(joinpath(d, name, "$(name)_graph_attributes.txt"))
        graph_attributes = readdlm(joinpath(d, name, "$(name)_graph_attributes.txt"), Float32)' |> collect
    else
        graph_attributes = nothing
    end

    TUData(st[:,1], st[:,2], 
            readdlm(joinpath(d, name, "$(name)_graph_indicator.txt"), Int) |> vec, 
            readdlm(joinpath(d, name, "$(name)_node_labels.txt"), Int) |> vec,
            edge_labels,            
            readdlm(joinpath(d, name, "$(name)_graph_labels.txt"), Int) |> vec,
            node_attributes, 
            edge_attributes,
            graph_attributes)
end


end #module 

